services:
  - type: web
    name: neuron
    runtime: node
    buildCommand:
    startCommand: HOST=localhost PORT=10000 npx y-websocket
    envVars:
      - key: PORT
        value: 10000
    ignorePaths:
      - src
    plan: free
